### ISSUE TITLE
Book Summary Missing from Content

### ISSUE THREAD

**Issue by edwoodward** [openstax/cnx-archive#362] opened 2015-10-06 02:25 UTC
User reported that the summary for a Book is missing on Rewrite. I confirmed that the Abstract in the json is null.

Rewrite json - http://archive.cnx.org/contents/98d253c0-8044-4e22-a707-7b8d819bc8a7@35.3.json

Legacy link with summary - http://legacy.cnx.org/content/col11642/latest

**Comment by karenc** [comment] 2017-07-31 22:22
Looking at the production database, I can confirm that all versions of col11642 have abstractid set to `21866`:

```
repository=# select * from abstracts where abstractid = 21866;
 abstractid |                                                                                                                          abstract                                                                                                                          | html 
------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------
      21866 | Over the years, Prof. Baldwin has published a large number of DSP tutorials. This collection, which is a work in process, gathers the more significant of those tutorials into a common location to make them more readily available for Connexions users. | 
(1 row)
```

There's no html abstract for some reason.  We probably need to run transforms on the abstract.

There are 2543 abstracts with no html abstracts:

```
repository=# select count(*) from abstracts where html is null;
 count
-------
  2543
(1 row)

```

**Comment by polanskers** [comment] 2017-08-02 16:30
Test script (test_producers.py) tests for plain text input and produces correct the result, so the transform code should work. Therefore, the problem is likely that the transform code triggered by the postgres table insert didn't get called.

A quick fix to insert the appropriate html is: 

`update abstracts set html = html_abstract(abstract) where html is null`

For the book summary above, this gives:
```
abstractid | 21866
abstract   | Over the years, Prof. Baldwin has published a large number of DSP tutorials. This collection, which is a work in process, gathers the more significant of those tutorials into a common location to make them more readily available for Connexions users.
html       | <div xmlns="http://www.w3.org/1999/xhtml" xmlns:c="http://cnx.rice.edu/cnxml" xmlns:md="http://cnx.rice.edu/mdml" xmlns:qml="http://cnx.rice.edu/qml/1.0" xmlns:mod="http://cnx.rice.edu/#moduleIds" xmlns:bib="http://bibtexml.sf.net/" xmlns:data="http://www.w3.org/TR/html5/dom.html#custom-data-attribute">Over the years, Prof. Baldwin has published a large number of DSP tutorials. This collection, which is a work in process, gathers the more significant of those tutorials into a common location to make them more readily available for Connexions users.</div>
```

**Comment by brittweinstein** [comment] 2019-02-22 21:54
CLOSING. If this presents itself as an issue again, we will reopen.

**Closed by brittweinstein** 2019-02-22 21:54 UTC
Labels: bug
